version: '3.9'

volumes:
    portainer:

services:
  portainer:
    image: portainer/portainer-ce
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - 9443:9443
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  # agent:
  #   image: portainer/agent
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #   deploy:
  #     mode: global
