version: '3.9'

volumes:
  prometheus:

services:
  prometheus:
    image: prom/prometheus
    # container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    deploy:
      replicas: 1
      placement: 
        constraints: [node.role == manager]
