version: '3.9'

volumes:
    gitlab_config:
    gitlab_logs:
    gitlab_data:

services:
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      # - 9443:443
      - 9080:80
      # - 9022:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
    shm_size: '256m'
