version: '3.9'

volumes:
    jenkins:

services:
  jenkins:
    image: jenkins/jenkins
    build: ./jenkins
    container_name: jenkins
    ports:
       - "8080:8080"
       - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID} 
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_LOCATION_URL=${JENKINS_LOCATION_URL}
      - GITLAB_URL=${GITLAB_URL}
