apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # editable: true
    # url: http://prometheus:9090
    url: $__env{PROMETHEUS_URL}
    access: proxy
    basicAuth: false
    version: 1